### ISSUE TITLE
[Bug]: 2 errors. Detected blocking call to listdir with args ('/config/gtfs2',) inside the event loop by custom integration 'gtfs2' at custom_components/gtfs2/gtfs

### ISSUE THREAD

**Issue by vlad36N** [vingerha/gtfs2#110]
### Own Analysis

- [X] I cannot find my issue in the documentation

### A clear and concise description of what the bug is.

```shell
Trying to install GTFS2 for HomeAssistant.
Using https://api-endpoint.mta.info/Dataservice/mtagtfsfeeds/nyct%2Fgtfs from https://api.mta.info/#/subwayRealTimeFeeds
```

### Provide details on the data source(s)

```shell
Using https://api-endpoint.mta.info/Dataservice/mtagtfsfeeds/nyct%2Fgtfs from https://api.mta.info/#/subwayRealTimeFeeds
```

### Config in case of setup using start / stop station

```shell
Did not finish setting db
```

### Config in case of setup using location based departures

```shell
Did not finish setting db
```

### Info on your installed version

Core 2024.10.4
Supervisor 2024.10.3
Operating System 13.2
Frontend 20241002.4

GTFS2 for HomeAssistant 0.5.1

### Relevant log output

```shell
Logger: homeassistant.util.loop
Source: util/loop.py:136
First occurred: 6:21:23 AM (1 occurrences)
Last logged: 6:21:23 AM

Detected blocking call to listdir with args ('/config/gtfs2',) inside the event loop by custom integration 'gtfs2' at custom_components/gtfs2/gtfs_helper.py, line 602: files = os.listdir(gtfs_dir) (offender: /config/custom_components/gtfs2/gtfs_helper.py, line 602: files = os.listdir(gtfs_dir)), please create a bug report at https://github.com/vingerha/gtfs2/issues For developers, please see https://developers.home-assistant.io/docs/asyncio_blocking_operations/#listdir Traceback (most recent call last): File "<frozen runpy>", line 198, in _run_module_as_main File "<frozen runpy>", line 88, in _run_code File "/usr/src/homeassistant/homeassistant/__main__.py", line 223, in <module> sys.exit(main()) File "/usr/src/homeassistant/homeassistant/__main__.py", line 209, in main exit_code = runner.run(runtime_conf) File "/usr/src/homeassistant/homeassistant/runner.py", line 189, in run return loop.run_until_complete(setup_and_run_hass(runtime_config)) File "/usr/local/lib/python3.12/asyncio/base_events.py", line 674, in run_until_complete self.run_forever() File "/usr/local/lib/python3.12/asyncio/base_events.py", line 641, in run_forever self._run_once() File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1990, in _run_once handle._run() File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run self._context.run(self._callback, *self._args) File "/usr/local/lib/python3.12/site-packages/aiohttp/web_protocol.py", line 556, in start task = asyncio.Task(coro, loop=loop, eager_start=True) File "/usr/local/lib/python3.12/site-packages/aiohttp/web_protocol.py", line 477, in _handle_request resp = await request_handler(request) File "/usr/local/lib/python3.12/site-packages/aiohttp/web_app.py", line 559, in _handle return await handler(request) File "/usr/local/lib/python3.12/site-packages/aiohttp/web_middlewares.py", line 117, in impl return await handler(request) File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 92, in security_filter_middleware return await handler(request) File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 83, in forwarded_middleware return await handler(request) File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 26, in request_context_middleware return await handler(request) File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 85, in ban_middleware return await handler(request) File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 242, in auth_middleware return await handler(request) File "/usr/src/homeassistant/homeassistant/components/http/headers.py", line 32, in headers_middleware response = await handler(request) File "/usr/src/homeassistant/homeassistant/helpers/http.py", line 73, in handle result = await handler(request, **request.match_info) File "/usr/src/homeassistant/homeassistant/components/http/decorators.py", line 81, in with_admin return await func(self, request, *args, **kwargs) File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 222, in post return await super().post(request, flow_id) File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 74, in wrapper return await method(view, request, data, *args, **kwargs) File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 122, in post result = await self._flow_mgr.async_configure(flow_id, data) File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 370, in async_configure result = await self._async_configure(flow_id, user_input) File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 413, in _async_configure result = await self._async_handle_step( File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 520, in _async_handle_step result: _FlowResultT = await getattr(flow, method)(user_input) File "/config/custom_components/gtfs2/config_flow.py", line 116, in async_step_local_stops datasources = get_datasources(self.hass, DEFAULT_PATH) File "/config/custom_components/gtfs2/gtfs_helper.py", line 602, in get_datasources files = os.listdir(gtfs_dir)


This error originated from a custom integration.

Logger: custom_components.gtfs2.gtfs_helper
Source: custom_components/gtfs2/gtfs_helper.py:415
integration: GTFS 2 (General Transit Feed Specification) (documentation, issues)
First occurred: 6:26:59 AM (1 occurrences)
Last logged: 6:26:59 AM

The given URL or GTFS data file/folder was not found
```

**Comment by vlad36N** [comment]
Tying to remove it and got error:
![mta_error](https://github.com/user-attachments/assets/1b64ac50-6db0-41f3-9dcc-928fba980ae0)

**Comment by vingerha** [comment]
Blocking call is already resolved in a dev release but is NOT a showstopper, the deleting one is new, will fix in the next few days.

The very first one is unclear to me, did you install using HA or gtfs2 on DEBUG ?

**Comment by vlad36N** [comment]
I did install GTFS2 on HA using HACS. Added integration.
Core 2024.10.4
Supervisor 2024.10.3
Operating System 13.2
Frontend 20241002.4

GTFS2 for HomeAssistant 0.5.1

**Comment by vingerha** [comment]
That is **not** the STATIC datasource, so logically it does not work, read the docs (not going to explain here)

**Comment by vlad36N** [comment]
/config/gtfs2 folder has been created and start the extraction to the sqlite database

**Comment by vlad36N** [comment]
This is exactly what I did and /config/gtfs2 folder has been created and start the extraction to the sqlite database. But then after couple minutes got error

**Comment by vingerha** [comment]
I am unsure how to get to your how your brain works (no offence meant, just not sure or my doc sucks)
** GTFS2 is setup around the 'static' gtfs data, scheduled trips when/where the vehicles run. On top of that you can add real-time data related to the point of departure as well as vehicle locations and alerts, depending on your transport provider. **

So logically (!) you cannot provide a REALTIME datasource when ti expects a STATIC one...

**Comment by vingerha** [comment]
Assuming doc sucks ( I am neither a developer nor a technical write) ...did a small update, hope this is more clear
https://github.com/vingerha/gtfs2/wiki/1.-Initial-setup:-the-static-data-source

**Comment by vlad36N** [comment]
I see, thank you

**Comment by vingerha** [comment]
Any improvement suggestions welcome of course

**Comment by vingerha** [comment]
'delete' issue fixed in latest beta release https://github.com/vingerha/gtfs2/releases/tag/0.5.2-beta5
