### ISSUE TITLE
[Bug]: Boston MBTA data does not import due to a cast from NoneType to float

### ISSUE THREAD

**Issue by mccollam** [vingerha/gtfs2#114]
### Own Analysis

- [X] I cannot find my issue in the documentation

### A clear and concise description of what the bug is.

```shell
Attempting to import the Boston MBTA GTFS data fails when processing stops.txt.  It appears that one of the fields is blank and fails when being cast to a float.

(This might be invalid data from the MBTA feed; I'm not familiar enough with GTFS to determine if this is failing on an optional field.)
```

### Provide details on the data source(s)

```shell
Data source URL: https://cdn.mbta.com/MBTA_GTFS.zip

I've tried with the latest version of the data (both via URL and uploading the zip, and confirmed the md5sum on the zip when copying it directly).
```

### Info on your installed version

gtfs2 version 0.5.4 on HAOS

Versions:
Core: 2024.12.0
Supervisor: 2024.11.4
OS: 14.0
Frontend:  20241127.4 

### Relevant log output

```shell
Loading GTFS data for <class 'pygtfs.gtfs_entities.Agency'>:
Loading GTFS data for <class 'pygtfs.gtfs_entities.Stop'>:
Loading GTFS data for <class 'pygtfs.gtfs_entities.Transfer'>:
Loading GTFS data for <class 'pygtfs.gtfs_entities.Route'>:
Loading GTFS data for <class 'pygtfs.gtfs_entities.Fare'>:
Loading GTFS data for <class 'pygtfs.gtfs_entities.FareRule'>:
Loading GTFS data for <class 'pygtfs.gtfs_entities.ShapePoint'>:
Loading GTFS data for <class 'pygtfs.gtfs_entities.Service'>:
Loading GTFS data for <class 'pygtfs.gtfs_entities.ServiceException'>:
Loading GTFS data for <class 'pygtfs.gtfs_entities.Trip'>:
Loading GTFS data for <class 'pygtfs.gtfs_entities.Frequency'>:
Loading GTFS data for <class 'pygtfs.gtfs_entities.StopTime'>:
Loading GTFS data for <class 'pygtfs.gtfs_entities.FeedInfo'>:
Loading GTFS data for <class 'pygtfs.gtfs_entities.Translation'>:
2 records read for <class 'pygtfs.gtfs_entities.Agency'>.
Process Process-2:
Traceback (most recent call last):
  File "/usr/local/lib/python3.13/multiprocessing/process.py", line 313, in _bootstrap
    self.run()
    ~~~~~~~~^^
  File "/usr/local/lib/python3.13/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/gtfs2/gtfs_helper.py", line 505, in extract_from_zip
    pygtfs.append_feed(gtfs, os.path.join(gtfs_dir, file))
    ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/pygtfs/loader.py", line 87, in append_feed
    instance = gtfs_class(feed_id=feed_id, **record._asdict())
  File "<string>", line 4, in __init__
  File "/usr/local/lib/python3.13/site-packages/sqlalchemy/orm/state.py", line 571, in _initialize_instance
    with util.safe_reraise():
         ~~~~~~~~~~~~~~~~~^^
  File "/usr/local/lib/python3.13/site-packages/sqlalchemy/util/langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/usr/local/lib/python3.13/site-packages/sqlalchemy/orm/state.py", line 569, in _initialize_instance
    manager.original_init(*mixed[1:], **kwargs)
    ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/sqlalchemy/orm/decl_base.py", line 2180, in _declarative_constructor
    setattr(self, k, kwargs[k])
    ~~~~~~~^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/sqlalchemy/orm/attributes.py", line 537, in __set__
    self.impl.set(
    ~~~~~~~~~~~~~^
        instance_state(instance), instance_dict(instance), value, None
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/local/lib/python3.13/site-packages/sqlalchemy/orm/attributes.py", line 1277, in set
    value = self.fire_replace_event(
        state, dict_, value, old, initiator
    )
  File "/usr/local/lib/python3.13/site-packages/sqlalchemy/orm/attributes.py", line 1292, in fire_replace_event
    value = fn(
        state, value, previous, initiator or self._replace_token
    )
  File "/usr/local/lib/python3.13/site-packages/sqlalchemy/orm/events.py", line 2573, in wrap
    return fn(target, *arg)
  File "/usr/local/lib/python3.13/site-packages/sqlalchemy/orm/util.py", line 328, in set_
    return validator(state.obj(), key, value)
  File "/usr/local/lib/python3.13/site-packages/pygtfs/gtfs_entities.py", line 73, in in_range
    float_value = float(value)
.Failure while writing Stops(stop_id='node-123-platform', stop_code=None, stop_name='Andrew', stop_desc='Andrew - Bottom of left outbound exit-only escalator', platform_code=None, stop_lat=None, stop_lon=None, zone_id=None, stop_url=None, location_type='3', parent_station='place-andrw', wheelchair_boarding='1')
TypeError: float() argument must be a string or a real number, not 'NoneType'
```

**Comment by mccollam** [comment]
Apologies, I see this is covered in #68 and the source referenced there seems to be unpacking.  Disappointing that the official feed is broken :(

Thanks for creating this and for your work tracking this down previously!

**Comment by vingerha** [comment]
Have a broken feed in the NL since last week :(
