### ISSUE TITLE
Issue adding Data Base

### ISSUE THREAD

**Issue by liammaclean** [vingerha/gtfs2#68]
**Describe the bug**
I've tried to add the MBTA Data base about 10 times over the last week and still no luck, never finishes extracting. (https://cdn.mbta.com/MBTA_GTFS.zip)

**Release used**
This is on Home Assistant on my Raspberry Pi 4

**Comment by vingerha** [comment]
Can you please add:
- what versoin of gtfs2
- the log that shows after you start downloading
- what do you see in the /gtfs2 folder

**Comment by liammaclean** [comment]
- The most recent install
- Logger: homeassistant.config_entries
Source: config_entries.py:2664
First occurred: 7:47:55 PM (1 occurrences)
Last logged: 7:47:55 PM

Error occurred loading flow for integration gtfs2: No module named 'google.transit'

- The gtfs2 folder has: MBTA.zip, MBTA.sqlite-journal, MBTA.sqlite

**Comment by vingerha** [comment]
Please provide a more complete set of logs, from the moment you submitted the request of a new datasource till and including the error. Start afresh, i.e. remove the MBTA files beforehand

**Comment by liammaclean** [comment]
I've attached both a screen shot of the file and the logs that I downloaded.![Screenshot_20240509-011633.png](https://github.com/vingerha/gtfs2/assets/6226041/e5ab8bb2-0080-4c32-a90c-e205fe2024c0)

![error_log.txt](https://github.com/vingerha/gtfs2/files/15257863/error_log.txt)

**Comment by vingerha** [comment]
There are no errors on gtfs except a statement: Cannot use this datasource as still unpacking: MBTA, this is because the journal file is stuck, I miss lots of log entries related to the unpacking itself
...please put the gtfs2 to debug  and add a new datasource with a slightly different name....then send me the logs

**Comment by liammaclean** [comment]
how do I put it to debug?

**Comment by vingerha** [comment]
If visible already (probably not as it is your first install)
![image](https://github.com/vingerha/gtfs2/assets/44190435/119ebea0-0961-4a21-9882-58ac7d827fd7)

Alternatively

configuration.yaml and restart HA 
```
logger:
  default: warning
  logs:
    custom_components.gtfs2: debug

**Comment by liammaclean** [comment]
Got it, ty. Here is what i have so far:
2024-05-09 01:56:36.275 DEBUG (SyncWorker_6) [custom_components.gtfs2.gtfs_helper] Getting gtfs with data: {'extract_from': 'url', 'file': 'MBTA2', 'url': 'https://cdn.mbta.com/MBTA_GTFS.zip'}
2024-05-09 01:56:36.277 DEBUG (SyncWorker_6) [custom_components.gtfs2.gtfs_helper] Checking if extracting: MBTA2
2024-05-09 01:56:43.722 INFO (SyncWorker_6) [custom_components.gtfs2.gtfs_helper] Exiting main after start subprocess for unpacking: MBTA2.zip
2024-05-09 01:56:43.731 DEBUG (MainThread) [custom_components.gtfs2.config_flow] Checkdata pygtfs: extracting with data: {'extract_from': 'url', 'file': 'MBTA2', 'url': 'https://cdn.mbta.com/MBTA_GTFS.zip'}

Will update if anything more is logged

**Comment by vingerha** [comment]
it should already show black-colored text with the entities that pygtfs is trying to extract

**Comment by liammaclean** [comment]
Nothing of that sort, this is the full of what I have:
2024-05-09 01:55:39.938 WARNING (SyncWorker_3) [homeassistant.loader] We found a custom integration hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-05-09 01:55:39.939 WARNING (SyncWorker_3) [homeassistant.loader] We found a custom integration gtfs2 which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-05-09 01:55:47.854 WARNING (MainThread) [homeassistant.helpers.frame] Detected that custom integration 'hacs' accesses hass.components.frontend. This is deprecated and will stop working in Home Assistant 2024.9, it should be updated to import functions used from frontend directly at custom_components/hacs/frontend.py, line 68: hass.components.frontend.async_register_built_in_panel(, please create a bug report at https://github.com/hacs/integration/issues
2024-05-09 01:55:50.865 ERROR (MainThread) [homeassistant.components.mqtt.client] Failed to connect to MQTT server due to exception: [Errno -5] Name has no usable address
2024-05-09 01:56:04.431 WARNING (MainThread) [homeassistant.helpers.frame] Detected that custom integration 'hacs' accesses hass.helpers.event. This is deprecated and will stop working in Home Assistant 2024.11, it should be updated to import functions used from event directly at custom_components/hacs/base.py, line 642: self.hass.helpers.event.async_track_time_interval(, please create a bug report at https://github.com/hacs/integration/issues
2024-05-09 01:56:36.275 DEBUG (SyncWorker_6) [custom_components.gtfs2.gtfs_helper] Getting gtfs with data: {'extract_from': 'url', 'file': 'MBTA2', 'url': 'https://cdn.mbta.com/MBTA_GTFS.zip'}
2024-05-09 01:56:36.277 DEBUG (SyncWorker_6) [custom_components.gtfs2.gtfs_helper] Checking if extracting: MBTA2
2024-05-09 01:56:43.722 INFO (SyncWorker_6) [custom_components.gtfs2.gtfs_helper] Exiting main after start subprocess for unpacking: MBTA2.zip
2024-05-09 01:56:43.731 DEBUG (MainThread) [custom_components.gtfs2.config_flow] Checkdata pygtfs: extracting with data: {'extract_from': 'url', 'file': 'MBTA2', 'url': 'https://cdn.mbta.com/MBTA_GTFS.zip'}

**Comment by vingerha** [comment]
meaning you have nothing more than this? doe sit stop reporting ar 01:56?

**Comment by liammaclean** [comment]
Yup, nothing beyond 1:56

**Comment by vingerha** [comment]
????? ...ok , I will try myself now...

**Comment by vingerha** [comment]
Hmm...I now see what you mean..the HA log is not showing all log entries.. I always use the container log and never look at HA..the container log shows this
```
2024-05-09 08:04:48.164 DEBUG (SyncWorker_2) [custom_components.gtfs2.gtfs_helper] Getting gtfs with data: {'extract_from': 'url', 'file': 'mbta2', 'url': 'https://cdn.mbta.com/MBTA_GTFS.zip'}
2024-05-09 08:04:48.168 DEBUG (SyncWorker_2) [custom_components.gtfs2.gtfs_helper] Checking if extracting: mbta2
2024-05-09 08:04:56.297 INFO (SyncWorker_2) [custom_components.gtfs2.gtfs_helper] Exiting main after start subprocess for unpacking: mbta2.zip
2024-05-09 08:04:56.310 DEBUG (MainThread) [custom_components.gtfs2.config_flow] Checkdata pygtfs: extracting with data: {'extract_from': 'url', 'file': 'mbta2', 'url': 'https://cdn.mbta.com/MBTA_GTFS.zip'}
Loading GTFS data for <class 'pygtfs.gtfs_entities.Agency'>:
Loading GTFS data for <class 'pygtfs.gtfs_entities.Stop'>:
Loading GTFS data for <class 'pygtfs.gtfs_entities.Transfer'>:
Loading GTFS data for <class 'pygtfs.gtfs_entities.Route'>:
Loading GTFS data for <class 'pygtfs.gtfs_entities.Fare'>:
Loading GTFS data for <class 'pygtfs.gtfs_entities.FareRule'>:
Loading GTFS data for <class 'pygtfs.gtfs_entities.ShapePoint'>:
Loading GTFS data for <class 'pygtfs.gtfs_entities.Service'>:
Loading GTFS data for <class 'pygtfs.gtfs_entities.ServiceException'>:
Loading GTFS data for <class 'pygtfs.gtfs_entities.Trip'>:
Loading GTFS data for <class 'pygtfs.gtfs_entities.Frequency'>:
Loading GTFS data for <class 'pygtfs.gtfs_entities.StopTime'>:
Loading GTFS data for <class 'pygtfs.gtfs_entities.FeedInfo'>:
Loading GTFS data for <class 'pygtfs.gtfs_entities.Translation'>:
2 records read for <class 'pygtfs.gtfs_entities.Agency'>.
Process Process-1:
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/usr/local/lib/python3.12/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/config/custom_components/gtfs2/gtfs_helper.py", line 429, in extract_from_zip
    pygtfs.append_feed(gtfs, os.path.join(gtfs_dir, file))
  File "/usr/local/lib/python3.12/site-packages/pygtfs/loader.py", line 87, in append_feed
    instance = gtfs_class(feed_id=feed_id, **record._asdict())
.Failure while writing Stops(stop_id='node-123-platform', stop_code=None, stop_name='Andrew', stop_desc='Andrew - Bottom of left outbound exit-only escalator', platform_code=None, stop_lat=None, stop_lon=None, zone_id=None, stop_url=None, location_type='3', parent_station='place-andrw', wheelchair_boarding='1')
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 4, in __init__
  File "/usr/local/lib/python3.12/site-packages/sqlalchemy/orm/state.py", line 564, in _initialize_instance
    with util.safe_reraise():
  File "/usr/local/lib/python3.12/site-packages/sqlalchemy/util/langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/usr/local/lib/python3.12/site-packages/sqlalchemy/orm/state.py", line 562, in _initialize_instance
    manager.original_init(*mixed[1:], **kwargs)
  File "/usr/local/lib/python3.12/site-packages/sqlalchemy/orm/decl_base.py", line 2142, in _declarative_constructor
    setattr(self, k, kwargs[k])
  File "/usr/local/lib/python3.12/site-packages/sqlalchemy/orm/attributes.py", line 537, in __set__
    self.impl.set(
  File "/usr/local/lib/python3.12/site-packages/sqlalchemy/orm/attributes.py", line 1277, in set
    value = self.fire_replace_event(
            ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/sqlalchemy/orm/attributes.py", line 1292, in fire_replace_event
    value = fn(
            ^^^
  File "/usr/local/lib/python3.12/site-packages/sqlalchemy/orm/events.py", line 2573, in wrap
    return fn(target, *arg)
           ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/sqlalchemy/orm/util.py", line 326, in set_
    return validator(state.obj(), key, value)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pygtfs/gtfs_entities.py", line 73, in in_range
    float_value = float(value)
                  ^^^^^^^^^^^^
TypeError: float() argument must be a string or a real number, not 'NoneType'

**Comment by liammaclean** [comment]
Where would I find container logs

**Comment by vingerha** [comment]
And this is the line that is frustrating, stop-code dannot be None
So as (sadly) often...the source data is incorrect.... check for posisble other sources ...e.g. on gtfs.pro

.Failure while writing Stops(stop_id='node-123-platform', stop_code=None, stop_name='Andrew', stop_desc='Andrew - Bottom of left outbound exit-only escalator', platform_code=None, stop_lat=None, stop_lon=None, zone_id=None, stop_url=None, location_type='3', parent_station='place-andrw', wheelchair_boarding='1')

**Comment by vingerha** [comment]
> Where would I find container logs

In the main container HA is running, but if yo uare on HAOS...that will not work easily....I am on docker/container version and using portainer

**Comment by liammaclean** [comment]
understood. Will you let me know if https://gtfs.pro/en/usa/Massachusetts-Bay-Transportation-Authority/boston-mbta works better for you? I'm trying it now, but if i can't see the logs i have no idea how I'll know if it is working or just stalling like before

**Comment by vingerha** [comment]
Am working on improving the logging....you can verify if the .sqlite grows...should become Mb

**Comment by liammaclean** [comment]
Yup, looks like it's growing now. Hope it works thanks so much for the help
