### ISSUE TITLE
Translink.ca Data Not Processing

### ISSUE THREAD

**Issue by latetedemelon** [vingerha/gtfs2#94]
**Describe the bug**

Essentially a minimal sqlite db is created and never populated.

Steps/data to reproduce the behavior, e.g.
- static data: https://gtfs-static.translink.ca/gtfs/History/2024-06-28/google_transit.zip
- route ID - 6672 (N/A as the zip doesn't unpack)
- stop ID - 4042 (N/A as the zip doesn't unpack)
- outward/return - N/A but are listed at 0/1.  stop id only has one direction for the route id.

**Release used**
- gtfs2 release -  0.4.8
- HA type (HAOS/Container) HAOS (VM)

**Additional**
Please add logs if helpfull, switch to 'debug' logging to get more details

2024-06-29 11:40:59.770 DEBUG (SyncWorker_23) [custom_components.gtfs2.gtfs_helper] Getting gtfs with data: {'extract_from': 'url', 'file': 'Translink', 'url': 'https://gtfs-static.translink.ca/gtfs/History/2024-06-28/google_transit.zip', 'api_key_name': 'api_key', 'api_key_location': 'not_applicable'}
2024-06-29 11:40:59.771 DEBUG (SyncWorker_23) [custom_components.gtfs2.gtfs_helper] Checking if extracting: Translink
2024-06-29 11:41:07.350 INFO (SyncWorker_23) [custom_components.gtfs2.gtfs_helper] Exiting main after start subprocess for unpacking: Translink.zip
2024-06-29 11:41:07.358 DEBUG (MainThread) [custom_components.gtfs2.config_flow] Checkdata pygtfs: extracting with data: {'extract_from': 'url', 'file': 'Translink', 'url': 'https://gtfs-static.translink.ca/gtfs/History/2024-06-28/google_transit.zip', 'api_key_name': 'api_key', 'api_key_location': 'not_applicable'}

**Comment by latetedemelon** [comment]
drwxr-xr-x    2 root     root          4096 Jun 29 11:41 .
drwxr-xr-x   11 root     root          4096 Jun 29 11:39 ..
-rw-r--r--    1 root     root        192512 Jun 29 11:41 Translink.sqlite
-rw-r--r--    1 root     root         41552 Jun 29 11:41 Translink.sqlite-journal
-rw-r--r--    1 root     root      13586307 Jun 29 11:41 Translink.zip

**Comment by vingerha** [comment]
Source incorrect... the logs show this shortly after kicking of adding a new datasource.
You will have to find another source, try gtfs pro or address this with your provider
```
Loading GTFS data for <class 'pygtfs.gtfs_entities.Translation'>:
1 record read for <class 'pygtfs.gtfs_entities.Agency'>.
Process Process-1:
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/usr/local/lib/python3.12/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/config/custom_components/gtfs2/gtfs_helper.py", line 445, in extract_from_zip
    pygtfs.append_feed(gtfs, os.path.join(gtfs_dir, file))
  File "/usr/local/lib/python3.12/site-packages/pygtfs/loader.py", line 87, in append_feed
    instance = gtfs_class(feed_id=feed_id, **record._asdict())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 4, in __init__
  File "/usr/local/lib/python3.12/site-packages/sqlalchemy/orm/state.py", line 564, in _initialize_instance
    with util.safe_reraise():
  File "/usr/local/lib/python3.12/site-packages/sqlalchemy/util/langhelpers.py", line 146, in __exit__
.8792 records read for <class 'pygtfs.gtfs_entities.Stop'>.
Failure while writing Transfers(from_stop_id='10744', to_stop_id='10744', transfer_type='4', min_transfer_time='0', from_trip_id='13910875', to_trip_id='13910904')
    raise exc_value.with_traceback(exc_tb)
  File "/usr/local/lib/python3.12/site-packages/sqlalchemy/orm/state.py", line 562, in _initialize_instance
    manager.original_init(*mixed[1:], **kwargs)
  File "/usr/local/lib/python3.12/site-packages/sqlalchemy/orm/decl_base.py", line 2142, in _declarative_constructor
    setattr(self, k, kwargs[k])
  File "/usr/local/lib/python3.12/site-packages/sqlalchemy/orm/attributes.py", line 537, in __set__
    self.impl.set(
  File "/usr/local/lib/python3.12/site-packages/sqlalchemy/orm/attributes.py", line 1277, in set
    value = self.fire_replace_event(
            ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/sqlalchemy/orm/attributes.py", line 1292, in fire_replace_event
    value = fn(
            ^^^
  File "/usr/local/lib/python3.12/site-packages/sqlalchemy/orm/events.py", line 2573, in wrap
    return fn(target, *arg)
           ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/sqlalchemy/orm/util.py", line 326, in set_
    return validator(state.obj(), key, value)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pygtfs/gtfs_entities.py", line 64, in in_range
    raise PygtfsValidationError(
pygtfs.exceptions.PygtfsValidationError: transfer_type must be in range [None, 0, 1, 2, 3], was 4

**Comment by vingerha** [comment]
Adding...with 'incorrect' I mean that the pygtfs library that I am using is not able to load that....I have no control over that library

**Comment by vingerha** [comment]
If ever you want to write to translink, then here is the definition...there is no type 4 
https://gtfs.org/schedule/best-practices/#transferstxt
